####  GET all categories
GET http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json

####  Create categories
POST http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

# data yang akan create
{
    "name" : "dayat"
}

##### GET By Id
GET http://localhost:3000/api/categories/4
X-API-Key: RAHASIA
Accept: application/json


##### Update Category By Id
PUT http://localhost:3000/api/categories/1
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

# data yang akan update
{
    "name" : "Sampo rejoiceEEE"
}


##### Delete Data By Id
DELETE http://localhost:3000/api/categories/13
X-API-Key: RAHASIA
Accept: application/json